name: Django CI

on: [push] #pull request

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipienv sync --dev

    - name: Run Flake8
      run: |
        pipenv run flake8 .
#    - name: Run Tests
#      run: |
#        pipenv manage.py test
